.TH install.sh 1 install.sh\-0.1
.SH NAME
install.sh \- installs/removes interactively the config of a2n-s on your arch machine.
.SH SYNOPSIS
.B ./install.sh
.RB [-hm]
.RB [+remove]
.RB [+install]
.RB [-H\=home]
.RB [-C\=config]
.RB [-S\=scripts]
.RB [-R\=repositories]
.RB [-D\=download]
.RB [-B\=binaries]
.RB [-L\=lazycli_release]
.SH DESCRIPTION
This is my install script.

One installs a snippet of my config with '+name-of-config-to-install' or removes one with '-name-of-config-to-remove'.

Note the use of '-' to remove stuff and '+' to indicate that the config should be installed.

Flags are here as preselections only. A popup editor will always open and let you modify the preferences for the installation process. The script tries to open $VISUAL, then $EDITOR and finally falls back to \`vi\` in case any of the previous two has been found.

There are four categories of config that one might find in my config files, with their particularities:
 - REPOS:
      They get installed, i.e. cloned in the \`$HDIR/$RDIR\` directory. The path is given in the flag name, e.g. the repo for my personal website in located at \`~/repos/sites\` under the name of \`a2n-s.github.io\`, thus the path is \`sites/a2n-s.github.io\`. Finally once the repo has been pulled, the origin should point towards my github account and the upstream is also set to reflect original forks.
      If the repo already exists on your machine, the install will prompt you to backup it and then retry.

 - SCRIPTS:
      All the scripts I use, the chosen ones will be installed under \`$HDIR/$SDIR\`.
      Your scripts, if in conflict with mine, will be backed up in \`$DIR/old/$SDIR\` to be recovered later.

 - CONFIG FILES:
      The config files I use. They will be installed either under \`$HDIR\` or \`$HDIR/$CDIR\`.
      Your config files, if in conflict with mine, will be backed up in \`$DIR/old\` or \`$DIR/old/$CDIR\` to be recovered later.

 - FONTS:
      coming soon...

See below how to modify the ENVIRONMENT variables to have a custom installation.
.SH OPTIONS
.TP
.B \-h \-\-help
Display the help message and exits without installing nor removing anything.
.TP
.B \-m \-\-man
Opens this pseudo man page.
.TP
.B \\-H=, \-\-home=, \-\-home-dir= home_directory
Changes the
.I home directory\fR.
Defaults to
.IR $HOME\fR.
.TP
.B \-C=, \-\-cfg=, \-\-config-dir= configuration_directory
Changes the
.I config directory\fR,
i.e. where most of the dotfiles are installed.
Defaults to
.IR .config\fR.
.TP
.B \-S=, \-\-src=, \-\-scripts-dir= scripts_directory
Changes the
.I scripts directory\fR,
i.e. where the scripts are installed.
Defaults to
.IR scripts\fR,
implicitely
.I $HOME/scripts
.TP
.B \-R=, \-\-repos=, \-\-repos-dir= repositories_directory
Changes the
.I repos directory\fR,
i.e. where the repositories are cloned.
Defaults to
.IR repos\fR,
implicitely
.I $HOME/repos
.TP
.B \-D=, \-\-dl=, \-\-download-dir= download_directory
Changes the
.I download directory\fR,
i.e. where things are downloaded.
Defaults to
.IR dl\fR,
implicitely
.I $HOME/dl
.TP
.B \-B=, \-\-bin=, \-\-binaries-dir= binaries_directory
Changes the
.I binaries directory\fR,
i.e. where the binaries are installed.
Defaults to
.IR .local/bin\fR,
implicitely
.I $HOME/.local/bin
.TP
.B \-L=, \-\-lcr=, \-\-lazycli-release= lazycli_release
Changes the
.I lazycli release\fR.
Defaults to
.IR https://github.com/jesseduffield/lazycli/releases/download/v0.1.15/lazycli-linux-x64.tar.gz\fR
as it is the latest release it the time.
.TP
.IB \-config_to_restore
Restore the specified config by using backup files and removing my files. See
.I below
for lists of
.I REPOS
,
.I SCRIPTS
,
.I CONFIGS
and
.I FONTS
.TP
.IB +config_to_install
Install the specified config on the machine. Back up files and takes care of, hopefully, everything. See
.I below
for lists of
.I REPOS
,
.I SCRIPTS
,
.I CONFIGS
and
.I FONTS
.SH REPOS:
.I prog/sketchbook/FastLED-basics
.I prog/scsc/fil-rouge
.I prog/scsc/fgk
.I prog/swarm-rescue-g1
.I sup/tatami
.I sup/machine-learning
.I sup/imgDesc
.I sup/flatland-project
.I sup/deep-learning
.I sup/stochastic
.I sup/mcdm
.I surf-src
.I yay-git
.I polybar-src
.I lazycli-src
.I dmscripts-src
.I dmenu-src
.I tabbed
.I slock
.I bash-insulter
.I kitty-src
.I Neovim-from-scratch
.I oh-my-bash
.I uzbl
.I oh-my-fish
.I a2n-s
.I wallpapers
.I oh-my-zsh
.I sites/nereuxofficial.github.io
.I sites/a2n-s.github.io/themes/hugo-theme-terminal
.I sites/a2n-s.github.io
.I dotfiles/atxr_dotfiles
.I research/playground_env
.I research/Imagine
.I research/imagineXdial
.I research/gym_ma_toy
.I research/learning-to-communicate-pytorch
.SH SCRIPTS:
.I _countdown.sh
.I _parse_git_info.sh
.I _shortwd.sh
.I _stopwatch.sh
.I dmrun.sh
.I hdmi.brightness.sh
.I lfrun.sh
.I list.git-repos.diagnostic.sh
.I misc.nvim-renaming.sh
.I open.sh
.I prompt.sh
.I repo.info.sh
.I repo.rename.default.branch.sh
.I screenshot.sh
.I slock-cst.sh
.I spectrWM-baraction.sh
.I surf-open.sh
.I togkb.sh
.I tr2md.sh
.I upl.sh
.I wvenv.sh
.I xtcl.sh
.I ytdl.sh
.SH MISCELLANEOUS CONFIG FILES:
.I git
.I htop
.I bash
.I fish
.I zsh
.I starship
.I neofetch
.I vim
.I neovim
.I x
.I bspwm
.I spectrwm
.I alacritty
.I kitty
.I nitrogen
.I slock
.I xscreensaver
.I polybar
.I vifm
.I lf
.I surf
.I tabbed
.I wallpapers
.I dmenu
.I dmscripts
.I lazygit
.I lazycli
.I tigrc
.I tmux
.I mpd
.I mpv
.I ncmpcpp
.I doom_emacs
.SH FONTS:
  coming soon...
.SH ENVIRONMENT
.B DIR
 directory where the config has been pulled, computed with pwd by install.sh
.TP
.B HDIR
.I $HOME
\- the Home DIRectory (HDIR)
.TP
.B CDIR
.I .config
\- the Configuration DIRectory (CDIR)
.TP
.B SDIR
.I scripts
\- the Scripts DIRectory (SDIR)
.TP
.B RDIR
.I repos
\- the Repositories DIRectory (RDIR)
.TP
.B DDIR
.I dl
\- the Download DIRectory (DDIR)
.TP
.B BDIR
.I .local/bin
\- the Binaries DIRectory (BDIR)
.SH EXAMPLES
\`./install.sh +bash -fish +bspwm +neovim +git\` will install \`bash\`, \`bspwm\`, \`neovim\` and \`git\` and remove \`fish\` to and from your config.
An editor will always popup to let you change the behaviour, but the config snippets above will be already preselected.
.SH AUTHOR
More about me and my config below:

  my personal page:
.I https://a2n-s.github.io/
  my github   page:
.I https://github.com/a2n-s
  my      dotfiles:
.I https://github.com/a2n-s/dotfiles
.SH REPORTING BUGS
       For bug reports, use the issue tracker at https://github.com/a2n-s/dotfiles/issues.
