#! /usr/bin/bash
#             ___
#       ____ |__ \ ____              _____      personal page: https://amtoine.github.io/ 
#      / __ `/_/ // __ \   ______   / ___/      github   page: https://github.com/amtoine 
#     / /_/ / __// / / /  /_____/  (__  )       my   dotfiles: https://github.com/amtoine/dotfiles 
#     \__,_/____/_/ /_/           /____/
#                               _____             __                    ____     __       __          __                          ____     __       __
#             _________  ____  / __(_)___ _     _/_/  ____  ___  ____  / __/__  / /______/ /_       _/_/        ____  ___  ____  / __/__  / /______/ /_  __________
#            / ___/ __ \/ __ \/ /_/ / __ `/   _/_/   / __ \/ _ \/ __ \/ /_/ _ \/ __/ ___/ __ \    _/_/         / __ \/ _ \/ __ \/ /_/ _ \/ __/ ___/ __ \/ ___/ ___/
#      _    / /__/ /_/ / / / / __/ / /_/ /  _/_/    / / / /  __/ /_/ / __/  __/ /_/ /__/ / / /  _/_/     _    / / / /  __/ /_/ / __/  __/ /_/ /__/ / / / /  / /__
#     (_)   \___/\____/_/ /_/_/ /_/\__, /  /_/     /_/ /_/\___/\____/_/  \___/\__/\___/_/ /_/  /_/      (_)  /_/ /_/\___/\____/_/  \___/\__/\___/_/ /_/_/   \___/
#                                 /____/
#
# Description:  my neofetch launch script -> launches a piece of ascii art based on the date.
# Dependencies: neofetch
# License:      https://github.com/amtoine/dotfiles/blob/main/LICENSE 
# Contributors: Stevan Antoine


art_dir=$HOME/.config/neofetch/ascii
# get the date as integer between 0 and 1231, i.e. the dates of the year.
DATE=$(date +"%m%d" | sed "s/^0\+//")
# write the output of neofetch to a special file.
ninfo="$HOME/.config/neofetch/.neofetchinfo"
# create the file if not already here.
if [[ ! -f $ninfo ]]; then touch $ninfo; fi
# put the output of neofetch inside the file.
neofetch --off > $ninfo

# check the date to adapt the image displayed.
# first, the narrowest events, i.e. a few days, e.g. birthdays.
if [ $DATE -eq 1105 ]; then
  neofetch --ascii $art_dir/lolo.art --ascii_colors 10 1 5 2 9 13
# then, medium sized events, e.g. christmas, holydays, halloween, ...
elif [ $DATE -ge 1024 -a $DATE -le 1107 ]; then
  neofetch --ascii $art_dir/halloween.art --ascii_colors 1 9
elif [ $DATE -ge 1215 -o $DATE -le 105 ]; then
  neofetch --ascii $art_dir/christmas.art --ascii_colors 7 7
# finally, seasons.
elif [ $DATE -ge 1221 -o $DATE -le 319 ]; then
  pr -mtJ $art_dir/winter-snow.art $ninfo
elif [ $DATE -ge 320 -a $DATE -le 620 ]; then
  pr -mtJ $art_dir/spring-flower.art $ninfo
elif [ $DATE -ge 621 -a $DATE -le 922 ]; then
  pr -mtJ $art_dir/summer-sun.art $ninfo
elif [ $DATE -ge 923 -a $DATE -le 1221 ]; then
  pr -mtJ $art_dir/fall-leaf.art $ninfo
# if nothing passed.
else
  pr -mtJ $art_dir/fall-leaf.art $ninfo
	# neofetch;
fi
