#! /usr/bin/bash
#*
#*                  _    __ _ _
#*   __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
#*  / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS:   https://github.com/goatfiles
#*  \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
#*  |___/
#*          MAINTAINERS:
#*              AMTOINE: https://github.com/amtoine antoine#1306 7C5EE50BA27B86B7F9D5A7BA37AAE9B486CFF1AB
#*              ATXR:    https://github.com/atxr    atxr#6214    3B25AF716B608D41AB86C3D20E55E4B1DE5B2C8B
#*

art_dir=$HOME/.config/neofetch/ascii
# get the date as integer between 0 and 1231, i.e. the dates of the year.
DATE=$(date +"%m%d" | sed "s/^0\+//")
# write the output of neofetch to a special file.
ninfo="$HOME/.config/neofetch/.neofetchinfo"
# create the file if not already here.
if [[ ! -f $ninfo ]]; then touch $ninfo; fi
# put the output of neofetch inside the file.
neofetch --off > $ninfo

# check the date to adapt the image displayed.
# first, the narrowest events, i.e. a few days, e.g. birthdays.
if [ $DATE -eq 1105 ]; then
  neofetch --ascii $art_dir/lolo.art --ascii_colors 10 1 5 2 9 13
# then, medium sized events, e.g. christmas, holydays, halloween, ...
elif [ $DATE -ge 1024 -a $DATE -le 1107 ]; then
  neofetch --ascii $art_dir/halloween.art --ascii_colors 1 9
elif [ $DATE -ge 1215 -o $DATE -le 105 ]; then
  neofetch --ascii $art_dir/christmas.art --ascii_colors 7 7
# finally, seasons.
elif [ $DATE -ge 1221 -o $DATE -le 319 ]; then
  pr -mtJ $art_dir/winter-snow.art $ninfo
elif [ $DATE -ge 320 -a $DATE -le 620 ]; then
  pr -mtJ $art_dir/spring-flower.art $ninfo
elif [ $DATE -ge 621 -a $DATE -le 922 ]; then
  pr -mtJ $art_dir/summer-sun.art $ninfo
elif [ $DATE -ge 923 -a $DATE -le 1221 ]; then
  pr -mtJ $art_dir/fall-leaf.art $ninfo
# if nothing passed.
else
  pr -mtJ $art_dir/fall-leaf.art $ninfo
	# neofetch;
fi
