#!/bin/sh
# a header could go here

tmpfile=$(mktemp /tmp/st-edit.XXXXXX)
trap  'rm "$tmpfile"' 0 1 15
cat > "$tmpfile"
if command -v devour &> /dev/null; then
  devour st -e "$EDITOR" "$tmpfile"
else
  st -e "$EDITOR" "$tmpfile"
fi
