"#######################
" set directories and runtime variables to
" unclutter the $HOME directory.
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif

"#######################
" some functions
function! ToggleLineNumber()
  if v:version > 703
    set relativenumber!
  else
    set nonumber!
  endif
endfunction

function! ToggleThemeMode(style)
    if a:style == "dark"
        set background=dark
        AirlineTheme tomorrow
        colorscheme Tomorrow-Night
    else
        set background=light
        colorscheme Tomorrow
        AirlineTheme tomorrow
    en
endfunction

function! s:build_quickfix_list(lines)
  call setqflist(map(copy(a:lines), '{ "filename": v:val }'))
  copen
  cc
endfunction

"#######################
" personal config.
set number
syntax on
set nowrap
set hlsearch
set tabstop=4 shiftwidth=4 expandtab
set list

set clipboard=unnamedplus

highlight RedundantSpaces ctermbg=red guibg=red
match RedundantSpaces /\s\+$/

" key bindings.
nmap ,gt :!tig --all<CR>
nmap ,gd :!TIGRC_USER="$HOME/.config/tig/.dotfiles" GIT_DIR="$HOME/.dotfiles" GIT_WORK_TREE="$HOME" tig --all<CR>
nmap ,gl :!lazygit<CR>
nmap ,so :source ~/.config/vim/vimrc<CR>
nmap ,cl :w<CR>:!latexmk -C; latexmk -shell-escape -pdf main.tex
nmap ,nh :nohlsearch<CR>
nmap ,, :!
nmap ,W :w !sudo tee %
nmap ,e :Ex<CR>
