#!/bin/sh
#             ___
#       ____ |__ \ ____              _____      personal page: https://a2n-s.github.io/ 
#      / __ `/_/ // __ \   ______   / ___/      github   page: https://github.com/a2n-s 
#     / /_/ / __// / / /  /_____/  (__  )       my   dotfiles: https://github.com/a2n-s/dotfiles 
#     \__,_/____/_/ /_/           /____/
#                _       _ __
#          _  __(_)___  (_) /___________
#         | |/_/ / __ \/ / __/ ___/ ___/
#      _ _>  </ / / / / / /_/ /  / /__
#     (_)_/|_/_/_/ /_/_/\__/_/   \___/
#
# Description:  my x config.
# Dependencies: picom, feh, a wm, xscreensaver.
# License:      https://github.com/a2n-s/dotfiles/blob/main/LICENSE 
# Contributors: Stevan Antoine



userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

### window manager launching:
# exec bspwm
exec qtile start
# exec spectrwm
# exec xmonad
# exec i3
# exec awesome
