#!/usr/bin/env bash
#             ___
#       ____ |__ \ ____              _____      personal page: https://a2n-s.github.io/ 
#      / __ `/_/ // __ \   ______   / ___/      github   page: https://github.com/a2n-s 
#     / /_/ / __// / / /  /_____/  (__  )       my   dotfiles: https://github.com/a2n-s/dotfiles 
#     \__,_/____/_/ /_/           /____/
#                               _____             __       __                         _       __             __                    _____
#             _________  ____  / __(_)___ _     _/_/  ____/ /___ ___  _______________(_)___  / /______     _/_/  _________  ____  / __(_)___ _
#            / ___/ __ \/ __ \/ /_/ / __ `/   _/_/   / __  / __ `__ \/ ___/ ___/ ___/ / __ \/ __/ ___/   _/_/   / ___/ __ \/ __ \/ /_/ / __ `/
#      _    / /__/ /_/ / / / / __/ / /_/ /  _/_/    / /_/ / / / / / (__  ) /__/ /  / / /_/ / /_(__  )  _/_/    / /__/ /_/ / / / / __/ / /_/ /
#     (_)   \___/\____/_/ /_/_/ /_/\__, /  /_/      \__,_/_/ /_/ /_/____/\___/_/  /_/ .___/\__/____/  /_/      \___/\____/_/ /_/_/ /_/\__, /
#                                 /____/                                           /_/                                               /____/
#
# Description:  all the config needed by the dmscripts.
# Dependencies: this is up to you.
# License:      https://github.com/a2n-s/dotfiles/blob/main/LICENSE 
# Contributors: Stevan Antoine

# shellcheck disable=SC2034
# This issue is ignored because it is part of a larger file that calls upon all variables listed

# Defined variables, modify anything in quotes to your prefered software

# -p is needed as we use prompts, alternative programs have to handle prompts well.

# DMENU="dmenu -i -l 20 -p"
DMWIDTH=1500
DMHEIGHT=10
DMCOLUMNS=2
DMLINES=9
DMBORDER=5
DMENU="dmenu -i -g $DMCOLUMNS -l $DMLINES -x $((960 - $DMWIDTH/2)) -y $((540 - ($DMLINES+1)*$DMHEIGHT/2)) -z $DMWIDTH -h $DMHEIGHT -bw $DMBORDER -p"

# DMBROWSER="brave"
DMBROWSER="surf"
# DMBROWSER="firefox"
# DMBROWSER="qutebrowser"

# DMTERM="st -e"
# DMTERM="alacritty -e"
DMTERM="kitty"

# DMEDITOR="emacsclient -c -a emacs"
DMEDITOR="${DMTERM} nvim"

# TODO: Rename this variable to something more traditional
# logout_locker='slock'
logout_locker="$HOME/scripts/slock-cst.sh"
# logout_locker='xscreensaver-command -lock'
# logout_locker='dm-tool lock'

# This case statement lets you change what the DMENU variable is for different scripts, so if you
# want a unique variable for each script you can
# syntax is as follows:
# "<ending-of-script>") DMENU="your variable here"
# *) should be left blank, global variables are defined above

# include -p in standard dmenu as we use prompts by default
case "${0##*-}" in
 "youtube") DMENU="dmenu -i -l 30 -p";;
  *);;
esac

# "${0##*-}" means grab the 0th argument (which is always the path to the program) starting from the
# last dash. This gives us the word after the - which is what we are searching for in the case
# statement. ie dm-man -> man

# An awk equivalent is:
# awk -F"-" '{print $NF}'
# Sadly cut has no easy equivalent

# TODO: Move almost all of these variables into the case statement
# TODO: Make some of the more useful ones general variables
# IE a pictures directory, an audio directory, config locations, etc

# dm-note
note_dir="${HOME}/.config/dmscripts/dmnote"

# dm-confedit
declare -A confedit_list
confedit_list[alacritty]="$HOME/.config/alacritty/alacritty.yml"
confedit_list[bashrc]="$HOME/.bashrc"
confedit_list[bash_profile]="$HOME/.bash_profile"
confedit_list[bash_logout]="$HOME/.bash_logout"
confedit_list[aliases]="$HOME/repos/oh-my-bash/custom/aliases/example.aliases.sh"
confedit_list[bspwm]="$HOME/.config/bspwm"
confedit_list[bspwmrc]="$HOME/.config/bspwm/bspwmrc"
confedit_list[confedit]="$HOME/.config/dmscripts/config"
confedit_list[dmscripts config]="$HOME/.config/dmscripts/config"
confedit_list[fish]="$HOME/.config/fish"
confedit_list[gitconfig]="$HOME/.gitconfig"
confedit_list[kitty]="$HOME/.config/kitty/kitty.conf"
confedit_list[lf]="$HOME/.config/lf/lfrc"
confedit_list[lazygit]="$HOME/.config/lazygit/config.yml"
confedit_list[lazycli]="$HOME/.config/lazycli/config.yml"
confedit_list[mpd]="$HOME/.config/mpd/mpd.conf"
confedit_list[mpv]="$HOME/.config/mpv"
confedit_list[neofetch]="$HOME/.config/neofetch"
confedit_list[ncmcpp]="$HOME/.config/ncmpcpp/config"
confedit_list[picom]="$HOME/.config/picom/picom.conf"
confedit_list[polybar]="$HOME/repos/polybar-themes"
confedit_list[profile]="$HOME/.profile"
#confedit_list[qutebrowser bookmarks]="$HOME/.config/qutebrowser/bookmarks/urls"
#confedit_list[qutebrowser quickmarks]="$HOME/.config/qutebrowser/quickmarks"
#confedit_list[qutebrowser config.py]="$HOME/.config/qutebrowser/config.py"
confedit_list[README.md]="$HOME/README.md"
confedit_list[scripts]="$HOME/scripts"
confedit_list[starship]="$HOME/.config/starship.toml"
confedit_list[spectrwm]="$HOME/.config/spectrwm/spectrwm.conf"
confedit_list[spectrwm_us]="$HOME/.config/spectrwm/spectrwm_us.conf"
confedit_list[spectrwm_fr]="$HOME/.config/spectrwm/spectrwm_fr.conf"
confedit_list[ssh]="$HOME/.ssh/config"
confedit_list[surf config]="$HOME/.config/surf"
confedit_list[surf bookmarks]="$HOME/.config/surf/bookmarks"
confedit_list[sxhkd]="$HOME/.config/sxhkd/sxhkdrc"
confedit_list[tmux.conf]="$HOME/.tmux.conf"
confedit_list[tigrc]="$HOME/.config/tigrc"
confedit_list[vifm]="$HOME/.config/vifm/vifmrc"
confedit_list[vim]="$HOME/.vimrc"
confedit_list[xinitrc]="$HOME/.xinitrc"
confedit_list[xresources]="$HOME/.Xresources"

confedit_list[a2n-s]="$HOME/repos/a2n-s"
confedit_list[dmenu]="$HOME/repos/dmenu"
confedit_list[dmscripts]="$HOME/repos/dmscripts"
confedit_list[kitty]="$HOME/repos/kitty"
confedit_list[oh-my-bash]="$HOME/repos/oh-my-bash"
confedit_list[oh-my-fish]="$HOME/repos/oh-my-fish"
confedit_list[oh-my-zsh]="$HOME/repos/oh-my-zsh"
confedit_list[polybar]="$HOME/repos/polybar"
confedit_list[sites]="$HOME/repos/sites"
confedit_list[surf]="$HOME/repos/surf"
confedit_list[slock]="$HOME/repos/slock"
confedit_list[tabbed]="$HOME/repos/tabbed"
confedit_list[uzbl]="$HOME/repos/uzbl"


# dm-reddit config
declare -a reddit_list=(
"r/archlinux"
"r/bash"
"r/commandline"
"r/emacs"
"r/freesoftware"
"r/linux"
"r/linux4noobs"
"r/linuxmasterrace"
"r/linuxquestions"
"r/suckless"
"r/Ubuntu"
"r/unixporn"
"r/vim"
)

# Search engine config
declare -A websearch
# Syntax:
# websearch[name]="https://www.example.com/search?q="

# Search Engines
websearch[bing]="https://www.bing.com/search?q="
websearch[brave]="https://search.brave.com/search?q="
websearch[duckduckgo]="https://duckduckgo.com/?q="
websearch[gemini search \(https\)]="https://portal.mozz.us/gemini/geminispace.info/search%3F"
websearch[google]="https://www.google.com/search?q="
websearch[qwant]="https://www.qwant.com/?q="
websearch[swisscows]="https://swisscows.com/web?query="
websearch[yandex]="https://yandex.com/search/?text="
# Information/News
websearch[bbcnews]="https://www.bbc.co.uk/search?q="
websearch[cnn]="https://www.cnn.com/search?q="
websearch[googlenews]="https://news.google.com/search?q="
websearch[wikipedia]="https://en.wikipedia.org/w/index.php?search="
websearch[wiktionary]="https://en.wiktionary.org/w/index.php?search="
# Social Media
websearch[reddit]="https://www.reddit.com/search/?q="
websearch[odysee]="https://odysee.com/$/search?q="
websearch[youtube]="https://www.youtube.com/results?search_query="
# Online Shopping
websearch[amazon]="https://www.amazon.com/s?k="
websearch[craigslist]="https://www.craigslist.org/search/sss?query="
websearch[ebay]="https://www.ebay.com/sch/i.html?&_nkw="
websearch[gumtree]="https://www.gumtree.com/search?search_category=all&q="
# Linux
websearch[archaur]="https://aur.archlinux.org/packages/?O=0&K="
websearch[archpkg]="https://archlinux.org/packages/?sort=&q="
websearch[archwiki]="https://wiki.archlinux.org/index.php?search="
websearch[debianpkg]="https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords="
# Development
websearch[github]="https://github.com/search?q="
websearch[gitlab]="https://gitlab.com/search?search="
websearch[googleOpenSource]="https://opensource.google/projects/search?q="
websearch[sourceforge]="https://sourceforge.net/directory/?q="
websearch[stackoverflow]="https://stackoverflow.com/search?q="
# Etc

# dm-youtube config
# Think of these as your "subscribed channels", name the channel in the square brackets then put the channel URL in the quotation marks
# Syntax: youtube_channels[name]="https://www.youtube.com/link/to/channel"

declare -A youtube_channels
youtube_channels[Étincelles, EPFL]="https://www.youtube.com/channel/UC0o_ULEdwva8ksC63qvxMAA"
youtube_channels[13 Block]="https://www.youtube.com/channel/UCWY75uWazCXwtobPO232qAA"
youtube_channels[2Cheese MilkShake]="https://www.youtube.com/channel/UCCC5_hzMojUE01etdJxVjAA"
youtube_channels[2CheeseMilkShake - Topic]="https://www.youtube.com/channel/UCSQgph4-9v9SN0TWPWZQWEw"
youtube_channels[2TH Officiel]="https://www.youtube.com/channel/UCm2nD8breD2X5DvYCnN_bCQ"
youtube_channels[3Blue1Brown]="https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw"
youtube_channels[47Ter]="https://www.youtube.com/channel/UC7HvOYL0E1yWe7Fp31TWvXQ"
youtube_channels[7 Jaws]="https://www.youtube.com/channel/UCjuBrpUqR5bFvZYOsRmFqJQ"
youtube_channels[75e Session]="https://www.youtube.com/channel/UCo1zHzOv9O6JuT-jGp_flKw"
youtube_channels[a-ha]="https://www.youtube.com/channel/UCeEi1My3KTXHT0SG1JkR9gA"
youtube_channels[AaRON]="https://www.youtube.com/channel/UCV-q3-VuGgYzDEFXYDxIZRw"
youtube_channels[Abrège]="https://www.youtube.com/channel/UCWimnuBF27nwOxgUBJ4qNeg"
youtube_channels[Achile]="https://www.youtube.com/channel/UC0lG2Ixze6G6beMjULun5qw"
youtube_channels[AcousticTrench]="https://www.youtube.com/channel/UCV-hwVczs0GQRApxZS4TUNA"
youtube_channels[Akim Omiri]="https://www.youtube.com/channel/UCbOdpYBG53zmFuDK0qaTSmw"
youtube_channels[Alice et Moi]="https://www.youtube.com/channel/UCj6rtx3HBZEEPAYd0mT2SvQ"
youtube_channels[ALKPOTE]="https://www.youtube.com/channel/UC5eyo1DYNuDKkIExfXKeGIg"
youtube_channels[Amixem]="https://www.youtube.com/channel/UCgvqvBoSHB1ctlyyhoHrGwQ"
youtube_channels[An\'Om x Vayn]="https://www.youtube.com/channel/UCtSeaEcC85sFVBybLkPNFNA"
youtube_channels[Angerfist]="https://www.youtube.com/channel/UCdluEI4RUCXmIgWyGmt5y9g"
youtube_channels[apilune]="https://www.youtube.com/channel/UCio0T1T1I-sTXJDuQuTip9Q"
youtube_channels[Ari Seff]="https://www.youtube.com/channel/UCIxertsVDip8QHpnhinkAow"
youtube_channels[Arma Jackson]="https://www.youtube.com/channel/UCla-BsUB_GekvCCIwd-gC1g"
youtube_channels[Arxiv Insights]="https://www.youtube.com/channel/UCNIkB2IeJ-6AmZv7bQ1oBYg"
youtube_channels[Asaf Avidan]="https://www.youtube.com/channel/UCAtSxW7FSDbzZqD-my6UW2A"
youtube_channels[AstronoGeek]="https://www.youtube.com/channel/UC5X4e8ScZI2AFd_vkjSoyoQ"
youtube_channels[AURORA]="https://www.youtube.com/channel/UCNjHgaLpdy1IMNK57pYiKiQ"
youtube_channels[Axiome]="https://www.youtube.com/channel/UCNHFiyWgsnaSOsMtSoV_Q1A"
youtube_channels[Axolot]="https://www.youtube.com/channel/UC2_OG1L8DLTzQ7UrZVOk7OA"
youtube_channels[Aypierre]="https://www.youtube.com/channel/UCA5sfitizqs1oEbB5KY4uKQ"
youtube_channels[B-NØM Music]="https://www.youtube.com/channel/UCMz09FwSJiEcDVDoEQGwOtA"
youtube_channels[Balade Mentale]="https://www.youtube.com/channel/UCS_7tplUgzJG4DhA16re5Yg"
youtube_channels[BASTILLEvideos]="https://www.youtube.com/channel/UC0q_PBWOkFe3SKllFXf3eWw"
youtube_channels[bbno$]="https://www.youtube.com/channel/UCC8FSfSnbjiZ6vGr68ZLtzg"
youtube_channels[Bekar NFR]="https://www.youtube.com/channel/UCOvYc9SLXqnfOB-jEiYo_Xg"
youtube_channels[Ben Eater]="https://www.youtube.com/channel/UCS0N5baNlQWJCUrhCEo8WlA"
youtube_channels[Ben Vallack]="https://www.youtube.com/channel/UC4NNPgQ9sOkBjw6GlkgCylg"
youtube_channels[BEN.]="https://www.youtube.com/channel/UCanCcT8_W0moKZutEnJdWSA"
youtube_channels[Berywam]="https://www.youtube.com/channel/UCxXFx2jz8N02sNqv1VeDEGA"
youtube_channels[Best Of Antoine Daniel]="https://www.youtube.com/channel/UCBuee5JCBlI_VuKjxmqtyUA"
youtube_channels[BiG HEATH]="https://www.youtube.com/channel/UCAANvWwf0p9UfKBD2Rgn5gg"
youtube_channels[Biga*Ranx]="https://www.youtube.com/channel/UCHJ-g0a43Jcp_xa1LPjQvaQ"
youtube_channels[Bigflo et Oli]="https://www.youtube.com/channel/UCp6bpinXPzdx7d7-gekWzZQ"
youtube_channels[Bigorneaux & Coquillages]="https://www.youtube.com/channel/UCWMYFDuCcvkmPiOf1RP_IKQ"
youtube_channels[Billie Eilish]="https://www.youtube.com/channel/UCiGm_E4ZwYSHV3bcW1pnSeQ"
youtube_channels[Billx Official]="https://www.youtube.com/channel/UCwGuOEGEQjT2Goecz3BCNfg"
youtube_channels[Birdy Nam Nam]="https://www.youtube.com/channel/UCOVkvGg2nfiuInRpIJgsxbA"
youtube_channels[Bob Lennon]="https://www.youtube.com/channel/UCo0U1tbk3YbqiLDhkeWOviQ"
youtube_channels[Booska-P]="https://www.youtube.com/channel/UCczuNg-bajJgZLYhrY7FpfA"
youtube_channels[Breakbot]="https://www.youtube.com/channel/UCH6TCcFxQjVHLEwcJ8iXusA"
youtube_channels[Brick Experiment Channel]="https://www.youtube.com/channel/UClsFdM0HzTdF1JYoraQ0aUw"
youtube_channels[Brodie Robertson]="https://www.youtube.com/channel/UCld68syR8Wi-GY_n4CaoJGA"
youtube_channels[Brulux Officiel]="https://www.youtube.com/channel/UCa4Pn-ln0eyqFHml6IwQRTA"
youtube_channels[Caballero & JeanJass]="https://www.youtube.com/channel/UCeg0PVLfsBKFLGd9V_EvbGA"
youtube_channels[Camélia Jordana]="https://www.youtube.com/channel/UCQUOX5YyYrgE5rKOPTcLm_w"
youtube_channels[CaravanPalace]="https://www.youtube.com/channel/UCKH9HfYY_GEcyltl2mbD5lA"
youtube_channels[Castor Mother]="https://www.youtube.com/channel/UCfO4BQD5_S1272GVmuXmTxA"
youtube_channels[CGP Grey]="https://www.youtube.com/channel/UC2C_jShtL725hvbm1arSV9w"
youtube_channels[chambrefroideprod]="https://www.youtube.com/channel/UC5LQaZr2hG6nIjDxWc3zs6g"
youtube_channels[Channel Tres]="https://www.youtube.com/channel/UCx0H8GdP66dOal6yTGQDpeA"
youtube_channels[Charlotte Cardin]="https://www.youtube.com/channel/UCIEcq0eG63LS-4J9M1qNj9Q"
youtube_channels[Chat Sceptique]="https://www.youtube.com/channel/UCOuIgj0CYCXCvjWywjDbauw"
youtube_channels[Chilla]="https://www.youtube.com/channel/UCKMd3Shk0viCnCs1nsSOibw"
youtube_channels[CHRIS]="https://www.youtube.com/channel/UCMDgD_erEoLUkrbvae4-Weg"
youtube_channels[CHRIS 2.0]="https://www.youtube.com/channel/UCRx4CFKzNz8Ojp_Hikkn7Tg"
youtube_channels[chrisatmachine]="https://www.youtube.com/c/ChrisAtMachine"
youtube_channels[Code Bullet]="https://www.youtube.com/channel/UC0e3QhIYukixgh5VVpKHH9Q"
youtube_channels[CodeParade]="https://www.youtube.com/channel/UCrv269YwJzuZL3dH5PCgxUw"
youtube_channels[COLAS BIM]="https://www.youtube.com/channel/UCBK2DclO34h6BDqqrh-drPw"
youtube_channels[COLAS BIM GAMING]="https://www.youtube.com/channel/UC9orcd4I_3Uy_8_UAz2r48g"
youtube_channels[COLORS]="https://www.youtube.com/channel/UC2Qw1dzXDBAZPwS7zm37g8g"
youtube_channels[Columbine]="https://www.youtube.com/channel/UCJQsU9zWJHUCp2Wr088UN-g"
youtube_channels[Computerphile]="https://www.youtube.com/channel/UC9-y-6csu5WGm29I7JiwpnA"
youtube_channels[Creel]="https://www.youtube.com/channel/UCq7dxy_qYNEBcHqQVCbc20w"
youtube_channels[CYRILmp4]="https://www.youtube.com/channel/UC-4M8AN08hw39nn2v91VuMQ"
youtube_channels[Cyrus North]="https://www.youtube.com/channel/UCah8C0gmLkdtvsy0b2jrjrw"
youtube_channels[D!NG]="https://www.youtube.com/channel/UClq42foiSgl7sSpLupnugGA"
youtube_channels[D. Ace Officiel]="https://www.youtube.com/channel/UCZ430y2VULo_kIPplRBgsaw"
youtube_channels[Darktek]="https://www.youtube.com/channel/UCMwR4ASVjad2nSXASTo8e_w"
youtube_channels[Davie504]="https://www.youtube.com/channel/UCgFvT6pUq9HLOvKBYERzXSQ"
youtube_channels[DeenBurbigo]="https://www.youtube.com/channel/UCk0FyZXVQ_FmGi-XP8YqYsg"
youtube_channels[Des Cuts & Des Zooms]="https://www.youtube.com/channel/UCFtaxL-IZiZHJqzxvv1LmZQ"
youtube_channels[Didi Chandouidoui]="https://www.youtube.com/channel/UCf0mOxfawezlHIVuHd3L2VA"
youtube_channels[Die Antwoord]="https://www.youtube.com/channel/UC6DicDItkLQ7N4ag1JS5mqg"
youtube_channels[DigiDigger]="https://www.youtube.com/channel/UCCa794oAhys-HzkqdfmnjdQ"
youtube_channels[Dimeh Todo]="https://www.youtube.com/channel/UCc10uwCHG3GXcuUsoOlHavA"
youtube_channels[DIMENSION]="https://www.youtube.com/channel/UCiw_8x43hludK0PhuN9AJGg"
youtube_channels[DirtyBiology]="https://www.youtube.com/channel/UCtqICqGbPSbTN09K1_7VZ3Q"
youtube_channels[DistroTube]="https://www.youtube.com/channel/UCVls1GmFKf6WlTraIb_IaJg"
youtube_channels[Dj Weedim]="https://www.youtube.com/channel/UCACYV5bhqgguyqRUJ_MDMRA"
youtube_channels[Doc Geraud]="https://www.youtube.com/channel/UCQfrSok6xuClEq8bOwiEWfA"
youtube_channels[Dorothée Pousséo]="https://www.youtube.com/channel/UCuj27gPDOWEPwwQe6j8SXQQ"
youtube_channels[Doums L\'Entourage]="https://www.youtube.com/channel/UCe8txrJC396zSzlv2FLCITg"
youtube_channels[Dr Nozman]="https://www.youtube.com/channel/UCWnfDPdZw6A23UtuBpYBbAg"
youtube_channels[Dr. Peacock]="https://www.youtube.com/channel/UCsq3H3cTxvDU1Mktk1DQVkA"
youtube_channels[Dream]="https://www.youtube.com/channel/UCTkXRDQl0luXxVQrRQvWS6w"
youtube_channels[Dream Team]="https://www.youtube.com/channel/UC9bvUn7x3IrZ4yMANYjexUw"
youtube_channels[DreamXD]="https://www.youtube.com/channel/UChU3JRloULzdFX3aCu7BiSA"
youtube_channels[Dude Perfect]="https://www.youtube.com/channel/UCRijo3ddMTht_IHyNSNXpNQ"
youtube_channels[e-penser \[archives\]]="https://www.youtube.com/channel/UCcziTK2NKeWtWQ6kB5tmQ8Q"
youtube_channels[Echelon]="https://www.youtube.com/channel/UCdlj_P8-ZdYZyJYYN4qmKQA"
youtube_channels[Eddy de Pretto]="https://www.youtube.com/channel/UCKt7TGLZ1d81OeyJemba8aA"
youtube_channels[eden dillinger]="https://www.youtube.com/channel/UCNnnnvJdlsVCdeSSTtnO6Gw"
youtube_channels[El Jj]="https://www.youtube.com/channel/UCgkhWgBGRp0sdFy2MHDWfSg"
youtube_channels[ElectroBOOM]="https://www.youtube.com/channel/UCJ0-OtVpF0wOKEqT2Z1HEtA"
youtube_channels[Epic Mountain Music]="https://www.youtube.com/channel/UCgDfzIiPpEHMmpkvRYs7x9w"
youtube_channels[Eta Musique]="https://www.youtube.com/channel/UCFYalvitTOU_uBNFRl_hI-Q"
youtube_channels[Euphonik]="https://www.youtube.com/channel/UCXhZbZqNnk03jZVQDDI-hXA"
youtube_channels[Experimentboy]="https://www.youtube.com/channel/UCvGag7MyHR8H9oRm9iL9Ifw"
youtube_channels[Felckin]="https://www.youtube.com/channel/UCPgH1KIGI1Zrp0mqy99kgkg"
youtube_channels[Fireship]="https://www.youtube.com/channel/UCsBjURrPoezykLs9EqgamOA"
youtube_channels[Flammable Maths]="https://www.youtube.com/channel/UCtAIs1VCQrymlAnw3mGonhw"
youtube_channels[Florence Porcel]="https://www.youtube.com/channel/UC9HapjjoLqdDNwKEWQRaiyA"
youtube_channels[Fouloscopie]="https://www.youtube.com/channel/UCLXDNUOO3EQ80VmD9nQBHPg"
youtube_channels[Franz Ferdinand]="https://www.youtube.com/channel/UCrvJwuMaOeKg1Rb062glUJQ"
youtube_channels[Freeze Corleone]="https://www.youtube.com/channel/UCKU0CiLJ075xJ7Pgq1N5L5g"
youtube_channels[FrenchBall]="https://www.youtube.com/channel/UCQ5nOq77BZoKN_sB2iZsJ6Q"
youtube_channels[Fundy]="https://www.youtube.com/channel/UCCE5NVlm0FhbunMMBT48WAw"
youtube_channels[FundyLIVE]="https://www.youtube.com/channel/UCJhTTqtsvThK99_IbNDtwSw"
youtube_channels[Gambi]="https://www.youtube.com/channel/UCicqCO-7o9d6D2888BJWZ8Q"
youtube_channels[GeorgeNotFound]="https://www.youtube.com/channel/UCA2tt9GSU2sl8rAqjlLR3mQ"
youtube_channels[GeorgeWasFound]="https://www.youtube.com/channel/UCtWJFkS6AQ4dQ_nUTBPWi4A"
youtube_channels[Georgioxv3]="https://www.youtube.com/channel/UCAkhlZVATV8Ky0SMt4xb4RA"
youtube_channels[Gonkee]="https://www.youtube.com/channel/UCG2IoSJBUhrGL8fb5stMCWw"
youtube_channels[Gonzi Channelcore]="https://www.youtube.com/channel/UCXdVtgy9XEHWqSz3n2ivluQ"
youtube_channels[Gorillaz]="https://www.youtube.com/channel/UCfIXdjDQH9Fau7y99_Orpjw"
youtube_channels[GORSKI Official Channel]="https://www.youtube.com/channel/UCLVX5J-HwTD-BR0o-82cHrg"
youtube_channels[Grant Sanderson]="https://www.youtube.com/channel/UC78Ib99EBhMN3NemVjYm3Ig"
youtube_channels[Graven - Développement]="https://www.youtube.com/channel/UCIHVyohXw6j2T-83-uLngEg"
youtube_channels[Greg Guillotin]="https://www.youtube.com/channel/UCM1c1okZ-7cPV7BEZ-pzUGg"
youtube_channels[Gringe Officiel]="https://www.youtube.com/channel/UCcbG0C6CZuPiQkkHxo_Prgw"
youtube_channels[Hamza]="https://www.youtube.com/channel/UCGdSAF50uDAxghTy_3MpKng"
youtube_channels[Hardware-Related Coding]="https://www.youtube.com/channel/UC8VOeUKN6JAZPKXiXw_EzRw"
youtube_channels[Hatik]="https://www.youtube.com/channel/UC2qYnTW-cuVAqghnekPU6Jg"
youtube_channels[Hippocampe Fou]="https://www.youtube.com/channel/UC_TF0o9fX25CW7ka6W7U11A"
youtube_channels[Holly Humberstone]="https://www.youtube.com/channel/UC0xtJUctDSc7QncZAHYU26g"
youtube_channels[Homo Fabulus]="https://www.youtube.com/channel/UC-Dmq5q3-FIBknv1TVIR__Q"
youtube_channels[Hugo Lisoir]="https://www.youtube.com/channel/UCDC6DBi0kRp6Jk21xqfvFLA"
youtube_channels[Hungry Music]="https://www.youtube.com/channel/UCrDeYr6rmcyKpaKFSywWchg"
youtube_channels[Hunter]="https://www.youtube.com/channel/UCIS1fhFKrVY90DgzZ4yvbDQ"
youtube_channels[Hygiène Mentale]="https://www.youtube.com/channel/UCMFcMhePnH4onVHt2-ItPZw"
youtube_channels[ici Amy Plant]="https://www.youtube.com/channel/UC9wzC5mFFcIdguoyveTo6Ng"
youtube_channels[ICO]="https://www.youtube.com/channel/UCQzRMPX5VvPkQeccJeJV7vA"
youtube_channels[IlluminaHD]="https://www.youtube.com/channel/UCYsOW2PkoNjdYol4ej8OYLw"
youtube_channels[Jabrils]="https://www.youtube.com/channel/UCQALLeQPoZdZC4JNUboVEUg"
youtube_channels[James Baker]="https://www.youtube.com/channel/UCv_sHjokZ9qISkIpmV2ptww"
youtube_channels[James Sharman]="https://www.youtube.com/channel/UCeRXQ_B5WZD3yjPly45myvg"
youtube_channels[Jamy - Epicurieux]="https://www.youtube.com/channel/UCG9G2dyRv04FDSH1FSYuLBg"
youtube_channels[jdh]="https://www.youtube.com/channel/UCUzQJ3JBuQ9w-po4TXRJHiA"
youtube_channels[Jelle\'s Marble Runs]="https://www.youtube.com/channel/UCYJdpnjuSWVOLgGT9fIzL0g"
youtube_channels[JewelUsain]="https://www.youtube.com/channel/UCFMH1P9XIgiPjJOwXPEIqOw"
youtube_channels[JHON RACHID]="https://www.youtube.com/channel/UCnzWXmq8l0TIguCPDsrY78Q"
youtube_channels[Jnr Slice Officiel]="https://www.youtube.com/channel/UCXeJbdm3GLoQw5qOS0oHsww"
youtube_channels[joanna]="https://www.youtube.com/channel/UCXN8fZKzbgUwKUYc4tL_jCQ"
youtube_channels[Joe Hisaishi Official]="https://www.youtube.com/channel/UCxyzciBLt1Hyw06dlqwAIkw"
youtube_channels[JOLLY Lyonzon]="https://www.youtube.com/channel/UCsYa_h03khu_bGCmzsApuZg"
youtube_channels[Josman]="https://www.youtube.com/channel/UCZz-I0tsMCqEirxCAjAiI0A"
youtube_channels[Joueur Du Grenier]="https://www.youtube.com/channel/UC_yP2DpIgs5Y1uWC0T03Chw"
youtube_channels[JOYCA]="https://www.youtube.com/channel/UCow2IGnug1l3Xazkrc5jM_Q"
youtube_channels[JOYCA - Topic]="https://www.youtube.com/channel/UCBNZiKATbjZ0MF-qdI-yt4w"
youtube_channels[Joyca Music]="https://www.youtube.com/channel/UCZakU1z0jijzvw940Hwmlxg"
youtube_channels[Joysad]="https://www.youtube.com/channel/UC4M9gnm0243vZjyWe5dGRVg"
youtube_channels[Julien Doré]="https://www.youtube.com/channel/UC_HN4UwLGkimyAzgfDhap9w"
youtube_channels[jäde yours]="https://www.youtube.com/channel/UCttH7ODjdEiBISk-pE1ja2w"
youtube_channels[K Camp]="https://www.youtube.com/channel/UC83Tvu566Glh1OJR4gTDFIg"
youtube_channels[Kendrick Lamar]="https://www.youtube.com/channel/UC3lBXcrKFnFAFkfVk5WuKcQ"
youtube_channels[KezahProd]="https://www.youtube.com/channel/UCSvyuHw1gWtOYQiUS7t3vtw"
youtube_channels[KIKESA]="https://www.youtube.com/channel/UCcX5UhgQ3fCSXpemJzEuZIw"
youtube_channels[Kiuvo Officiel]="https://www.youtube.com/channel/UCx34fsksK2XWktpzJS9NlyQ"
youtube_channels[Koba LaD]="https://www.youtube.com/channel/UCCSFseZ6DfCtVO8giGp7GfA"
youtube_channels[KSHMR]="https://www.youtube.com/channel/UCFMjkrMT7Gvg84v0av-DIwA"
youtube_channels[Kurzgesagt – In a Nutshell]="https://www.youtube.com/channel/UCsXVk37bltHxD1rDPwtNM8Q"
youtube_channels[L\'histoire racontée par des chaussettes]="https://www.youtube.com/channel/UCrp9ngtJ52JQ3XM1RF9rNIg"
youtube_channels[L\'Or du Commun]="https://www.youtube.com/channel/UC_b01YmccNwcGGegEqBcsxg"
youtube_channels[L.E.J]="https://www.youtube.com/channel/UCRctnXfqPKaB4Ywp0y94ZDg"
youtube_channels[La Carologie]="https://www.youtube.com/channel/UCxQcOTjUpeI8Goo6UXJ2NgA"
youtube_channels[La chaîne de P.A.U.L]="https://www.youtube.com/channel/UCS-NkJiYhYku2YtKi2W4p3w"
youtube_channels[La Femme]="https://www.youtube.com/channel/UCIVKqDHYh8eidalfpfip2Wg"
youtube_channels[La P\'tite Fumée]="https://www.youtube.com/channel/UCwXEuIq6bAlYr_hdtSpv2jQ"
youtube_channels[La Tronche en Biais]="https://www.youtube.com/channel/UCq-8pBMM3I40QlrhM9ExXJQ"
youtube_channels[Lala &ce]="https://www.youtube.com/channel/UCh3J3l2nXAf-T17aBJfbUEQ"
youtube_channels[Lanterne Cosmique]="https://www.youtube.com/channel/UCWYxQt9Y3y2CDzXLf2K7xCA"
youtube_channels[Lasco]="https://www.youtube.com/channel/UCmCsV6pjdGluwL9if3UqoQA"
youtube_channels[LauCarré]="https://www.youtube.com/channel/UC7QfeEQ18LHJctDKeIOeGiw"
youtube_channels[Le Monde]="https://www.youtube.com/channel/UCYpRDnhk5H8h16jpS84uqsA"
youtube_channels[Le Monde à L\'Envers]="https://www.youtube.com/channel/UCeqsLJGWhZXEerY5JWvwLkg"
youtube_channels[le rappeur damso]="https://www.youtube.com/channel/UCxsYR3_7CKZeRfdJpqGxmdw"
youtube_channels[Le Règlement]="https://www.youtube.com/channel/UCcqe1EHmdaLVBwfqk5OtmXw"
youtube_channels[Le Sense Of Wonder]="https://www.youtube.com/channel/UCjsHDXUU3BjBCG7OaCbNDyQ"
youtube_channels[Le Tatou]="https://www.youtube.com/channel/UCR9DNIWLeXKQh_ZJWeXAl5Q"
youtube_channels[Le Vortex - ARTE ]="https://www.youtube.com/channel/UCZxLew-WXWm5dhRZBgEFl-Q"
youtube_channels[Le Wanski]="https://www.youtube.com/channel/UCPtTIYromdoe5xqQNwKMB-A"
youtube_channels[LEFA]="https://www.youtube.com/channel/UCnKCBjL2VJipAhyz6n2AeOg"
youtube_channels[Leios Labs]="https://www.youtube.com/channel/UCd0dc7kQA1FUpJ76o1EjLqQ"
youtube_channels[Leo Roi]="https://www.youtube.com/channel/UCBzxtDhnU8J59TKvhUIOYGA"
youtube_channels[Les Alchimistes]="https://www.youtube.com/channel/UCU2W6Yj5ry_n89hdne_u2tQ"
youtube_channels[Les Freres Poulain]="https://www.youtube.com/channel/UCjED9uS41ioeFuPfbR-OBlw"
youtube_channels[Les Kassos]="https://www.youtube.com/channel/UCv88958LRDfndKV_Y7XmAnA"
youtube_channels[LesAnticipateurs]="https://www.youtube.com/channel/UC725ySNLBEjHTRakayL74dA"
youtube_channels[Leto]="https://www.youtube.com/channel/UCP9zhgBhlIwgF5UEf3Pmj8Q"
youtube_channels[Lil Joyca]="https://www.youtube.com/channel/UCgANFlYnbE47942AoazfNsg"
youtube_channels[LincaTV]="https://www.youtube.com/channel/UCIeD9nXMZmJWeq3zl3UtA9w"
youtube_channels[Linguisticae]="https://www.youtube.com/channel/UCofQxJWd4qkqc7ZgaLkZfcw"
youtube_channels[Little Big]="https://www.youtube.com/channel/UCu7TZ_ATWgjgD9IrNLdnYDA"
youtube_channels[Livaï Off]="https://www.youtube.com/channel/UCn5TXAY8hdoG34goIzf-Tbg"
youtube_channels[Logic]="https://www.youtube.com/channel/UC4EDjfs78AhVgpBqE3WFGJg"
youtube_channels[LogicalGeekBoy]="https://www.youtube.com/channel/UCJx74HaacAjDZk8LPdOfUFQ"
youtube_channels[Lolo Zouaï]="https://www.youtube.com/channel/UCFlQ8q0A6zC-54DrSbX4UHQ"
youtube_channels[Lomepal]="https://www.youtube.com/channel/UCqswLq9y07OU_NNQKaSyoBQ"
youtube_channels[London Grammar]="https://www.youtube.com/channel/UC1oCOqdqlNDz5Sxnlk08ZrQ"
youtube_channels[Lorage]="https://www.youtube.com/channel/UCrBg36uOObPqoTp2tj4r5RQ"
youtube_channels[Lord Esperanza]="https://www.youtube.com/channel/UCE4Ykh2JJKBmS_Gf2o5cqIg"
youtube_channels[Lorenzo]="https://www.youtube.com/channel/UCrQjCrWOS63rBxO15TA5CfQ"
youtube_channels[Lorenzo VEVO]="https://www.youtube.com/channel/UCp-oJIAot-rMOHB2gWehzOA"
youtube_channels[Loud Officiel]="https://www.youtube.com/channel/UCTrRtszYvMOgEqL4ClnS7PQ"
youtube_channels[Low Level Learning]="https://www.youtube.com/channel/UC6biysICWOJ-C3P4Tyeggzg"
youtube_channels[Lujipeka]="https://www.youtube.com/channel/UC-4NatkpQeYGNjFY4brrJzw"
youtube_channels[LuvResval]="https://www.youtube.com/channel/UCPj63YTEirrOXgCp5xiBYJQ"
youtube_channels[Lycos]="https://www.youtube.com/channel/UC6l99GHukeTBrfmGVwi_RLQ"
youtube_channels[Lyonzon 69]="https://www.youtube.com/channel/UCtvTE64cO4YCheMmCn9rnmQ"
youtube_channels[Léopold]="https://www.youtube.com/channel/UCGfys_ojj4e-oN0adNX6siw"
youtube_channels[Madame Monsieur]="https://www.youtube.com/channel/UCiI-vXCD2rlCIsXVavrCJmg"
youtube_channels[Maghla]="https://www.youtube.com/channel/UChzNfUfgk7sQ5VOdy2r1Jow"
youtube_channels[MAKALA]="https://www.youtube.com/channel/UCg20mF_zavsqCjjERZqyyPw"
youtube_channels[Malaa]="https://www.youtube.com/channel/UCIyzc4i5ewvmJLzHFF4G5kw"
youtube_channels[Mandragora]="https://www.youtube.com/channel/UCCiKQNEkXQ1yEMZFr5pCA-w"
youtube_channels[Mangemort Squad]="https://www.youtube.com/channel/UCaW8nWryLD0TunnyUYqp5dQ"
youtube_channels[MARNIK]="https://www.youtube.com/channel/UCfz5we5RWJL0cLnYfRwwE7w"
youtube_channels[Mastu]="https://www.youtube.com/channel/UCAhaFPP6v3WCfK5Tjao0B7A"
youtube_channels[MastuTV]="https://www.youtube.com/channel/UCLnv0iKl-QbLnkuF-aSZKTQ"
youtube_channels[Mathologer]="https://www.youtube.com/channel/UC1_uAIS3r8Vu6JjXWvastJg"
youtube_channels[Mathologer 2]="https://www.youtube.com/channel/UCH74Hc_7WYVzx1GXhLEH6Eg"
youtube_channels[Matou]="https://www.youtube.com/channel/UC1u24fhJpejLDv6dU7iEwiQ"
youtube_channels[Matt_Parker_2]="https://www.youtube.com/channel/UCzV9N7eGedBchEQjQhPapyQ"
youtube_channels[Max Bird]="https://www.youtube.com/channel/UC-4WUubuVGowG_R7gdgesPA"
youtube_channels[Maxence]="https://www.youtube.com/channel/UCLcUntFF_kV9mI4YjpAL1Qw"
youtube_channels[mc bess]="https://www.youtube.com/channel/UCtGBG1M175UvlMJEocYaadg"
youtube_channels[Mcfly et Carlito]="https://www.youtube.com/channel/UCDPK_MTu3uTUFJXRVcTJcEw"
youtube_channels[Mcfly et Carlito la chaîne secondaire]="https://www.youtube.com/channel/UCtxhwJ-6n4_C6ElALThD25Q"
youtube_channels[mCoding]="https://www.youtube.com/channel/UCaiL2GDNpLYH6Wokkk1VNcg"
youtube_channels[Meduza]="https://www.youtube.com/channel/UC65kzmQBQ-hdEIS5THSOUtA"
youtube_channels[Michael Bronstein]="https://www.youtube.com/channel/UCVt9rN2LzKzNwJG-VXvZGkA"
youtube_channels[Michel]="https://www.youtube.com/channel/UCXl0qYV97iychaUIWLIR7KQ"
youtube_channels[Mickaël Launay]="https://www.youtube.com/channel/UC4PasDd25MXqlXBogBw9CAg"
youtube_channels[Miegakure]="https://www.youtube.com/channel/UCNqSF-tYoFYFxa7aayp_wiA"
youtube_channels[Minecraft Manhunt]="https://www.youtube.com/channel/UC2EQTEfNO6Uzx84IvJjjE-Q"
youtube_channels[Mister V]="https://www.youtube.com/channel/UC8Q0SLrZLiTj5s4qc9aad-w"
youtube_channels[Mister V Music]="https://www.youtube.com/channel/UCGbkLk615v-fh5Qgc6b-TVQ"
youtube_channels[Monkey Dee Youv]="https://www.youtube.com/channel/UCiEQTnvUaRLgwdPhqJRqPRg"
youtube_channels[Monsieur Phi]="https://www.youtube.com/channel/UCqA8H22FwgBVcF3GJpp0MQw"
youtube_channels[MrBboy45]="https://www.youtube.com/channel/UC33lqxChj2yKSoSjK6NWkZQ"
youtube_channels[MrSuicideSheep]="https://www.youtube.com/channel/UC5nc_ZtjKW1htCVZVRxlQAQ"
youtube_channels[MsBgirl45]="https://www.youtube.com/channel/UCqrtWbyOj-LA4hvdb7zyVPg"
youtube_channels[Mutual Information]="https://www.youtube.com/channel/UCCcrR0XBH0aWbdffktUBEdw"
youtube_channels[Nanek]="https://www.youtube.com/channel/UCFMMQTLgdW19Ewf7ROxhnOw"
youtube_channels[Naâman Official]="https://www.youtube.com/channel/UCOxnDkpY5EgqH4YqE4lHuxQ"
youtube_channels[NEMIRNEMS]="https://www.youtube.com/channel/UCVN7uXZrWcXdyyMZGOLyWEA"
youtube_channels[Nepal - Topic]="https://www.youtube.com/channel/UCdWGxWejEXZrKMz8Br37Glg"
youtube_channels[Night Lovell]="https://www.youtube.com/channel/UCjwf9oA4C9Yzxcg4vjI5GDg"
youtube_channels[Ninho]="https://www.youtube.com/channel/UCXdHJabqwLJ3NvPfx6XmS5Q"
youtube_channels[Nota Bene]="https://www.youtube.com/channel/UCP46_MXP_WG_auH88FnfS1A"
youtube_channels[Numberphile]="https://www.youtube.com/channel/UCoxcjq-8xIDTYp3uz647V5A"
youtube_channels[Numberphile2]="https://www.youtube.com/channel/UCyp1gCHZJU_fGWFf2rtMkCg"
youtube_channels[Nusky]="https://www.youtube.com/channel/UCUak4byYyCGpyvpu-v17Rdw"
youtube_channels[NuskyVaatiVEVO]="https://www.youtube.com/channel/UCc9-iPl_atZJ2FT79JmzNEQ"
youtube_channels[odezenne]="https://www.youtube.com/channel/UCstYELvMHHhLQfYHEZhYNng"
youtube_channels[Officiel DEFAKATOR]="https://www.youtube.com/channel/UCU0FhLr6fr7U9GOn6OiQHpQ"
youtube_channels[Oklou]="https://www.youtube.com/channel/UCPmfaXPGbC03r30Q5eR5atw"
youtube_channels[omido]="https://www.youtube.com/channel/UCkxa9ydfsyR6EtvH4AWmvLg"
youtube_channels[orelsan]="https://www.youtube.com/channel/UCEnFzIYw3BrndPCddyQ6c5A"
youtube_channels[Origami with Jo Nakashima]="https://www.youtube.com/channel/UC3ICcukYYeSn26KlCRnhOhA"
youtube_channels[Oscar Anton]="https://www.youtube.com/channel/UCMu7q-D4nxTUCr6gCoUk-cQ"
youtube_channels[OWSLA]="https://www.youtube.com/channel/UC8nidfOKkcgpO6tfc9OSdBQ"
youtube_channels[Oxmo Puccino \[Officiel\]]="https://www.youtube.com/channel/UCXMsmrUmeJBdtKEDREREv-w"
youtube_channels[Panda Dub]="https://www.youtube.com/channel/UCg3X4g3oKr1AQFnkM-dCR_Q"
youtube_channels[Pandrezz]="https://www.youtube.com/channel/UCwwxREa1Rm9vh0On9bRWo_Q"
youtube_channels[Passe-Science]="https://www.youtube.com/channel/UCsz9DiwPtgDvxJ-njWnieZw"
youtube_channels[PATAPOUFGANG]="https://www.youtube.com/channel/UCF5PlHGBfShLo8OHA0wwrkA"
youtube_channels[Paul Law]="https://www.youtube.com/channel/UCDn07eKw2HDPIgSAGQgliAA"
youtube_channels[PAUSE PROCESS]="https://www.youtube.com/channel/UC0JUkXAVVA4qWH1BQRs5N3A"
youtube_channels[Petit Voyou]="https://www.youtube.com/channel/UCtOIFqhJGOTZdT2raQc8VpQ"
youtube_channels[phelto]="https://www.youtube.com/channel/UCSrg8YPpUJDNNVL1RxadCFw"
youtube_channels[Physics Girl]="https://www.youtube.com/channel/UC7DdEm33SyaTDtWYGO2CwdA"
youtube_channels[Pink Noise]="https://www.youtube.com/channel/UCyVax3AQfKeuiuOyg0DucEQ"
youtube_channels[PLK TV]="https://www.youtube.com/channel/UCL6gZm742-Xhxp4Cwa6kqpw"
youtube_channels[PNL]="https://www.youtube.com/channel/UCtBjt766LG9EDVKZx4Q4IHw"
youtube_channels[PNL WORLD]="https://www.youtube.com/channel/UCIh4fbWil1PPwvSxA1bAl2A"
youtube_channels[Polo & Pan]="https://www.youtube.com/channel/UCQUFWrwQshjbq3VN0yfm_5Q"
youtube_channels[PommeMusic]="https://www.youtube.com/channel/UCZy0-5YHgLpzgT-biGtJgJg"
youtube_channels[Poupie]="https://www.youtube.com/channel/UC4N3njjvdn9OfpkzaBnxkBA"
youtube_channels[Powfu]="https://www.youtube.com/channel/UCmR-xOM0ZjY1cPdFp2WXT4g"
youtube_channels[Primer]="https://www.youtube.com/channel/UCKzJFdi57J53Vr_BkTfN3uQ"
youtube_channels[Primum Non Nocere]="https://www.youtube.com/channel/UC9BnGZLT4iPaJtDOXYwQuHQ"
youtube_channels[pvnova]="https://www.youtube.com/channel/UCB0qpLkjzVlVZ4c8nKiCEyw"
youtube_channels[Reducible]="https://www.youtube.com/channel/UCK8XIGR5kRidIw2fWqwyHRA"
youtube_channels[Remzcore]="https://www.youtube.com/channel/UCxJ5wHDqQcCWs771UxeIFjg"
youtube_channels[Reta]="https://www.youtube.com/channel/UC_NSOPMFJXCNJLoyjd2rhfg"
youtube_channels[REZZ]="https://www.youtube.com/channel/UCMcWPM9eOz9Dsn7YwAlpOoQ"
youtube_channels[Rilès]="https://www.youtube.com/channel/UC-NwsBEyZqZnPc9OaCFJSsw"
youtube_channels[Risque Alpha]="https://www.youtube.com/channel/UCJ7_Ld2cIVY5MM3NcKW3D8A"
youtube_channels[Robert Miles]="https://www.youtube.com/channel/UCLB7AzTwc6VFZrBsO2ucBMg"
youtube_channels[Roméo Elvis]="https://www.youtube.com/channel/UCrLTHz-a-RgeVCkx4iOhs0w"
youtube_channels[Ruskov]="https://www.youtube.com/channel/UCE8q-CUstv-HicI8d6-n0LA"
youtube_channels[Règlement Radio]="https://www.youtube.com/channel/UCsb692t2JYv9UrubQeTfqLA"
youtube_channels[Sadek]="https://www.youtube.com/channel/UCI0fO--ObkF3KuRj7vvXazw"
youtube_channels[San-Nom]="https://www.youtube.com/channel/UCKTHzUOy46AgKnENDWsezMQ"
youtube_channels[SANTA SALUT]="https://www.youtube.com/channel/UCYhiDGVTQHHkS_1khuLqlgA"
youtube_channels[Sapnap]="https://www.youtube.com/channel/UCqynl7rdtktKMQESdSBmE-g"
youtube_channels[Savage Toddy]="https://www.youtube.com/channel/UC2fC-4EBKf3nus9Q6G3do2g"
youtube_channels[SCH]="https://www.youtube.com/channel/UCeBu6AFsaPVElhFzlj5hetg"
youtube_channels[Science4All]="https://www.youtube.com/channel/UC0NCbj8CxzeCGIF6sODJ-7A"
youtube_channels[ScienceClic]="https://www.youtube.com/channel/UCV6uM3y-8TeO7JlCtcEN-Bg"
youtube_channels[ScienceEtonnante]="https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA"
youtube_channels[Scilabus]="https://www.youtube.com/channel/UCeR8BYZS7IHYjk_9Mh5JgkA"
youtube_channels[Scinéma]="https://www.youtube.com/channel/UCPF7JOWMDWZmnP_cQfyAezg"
youtube_channels[Scyllaofficiel]="https://www.youtube.com/channel/UCz3KCKF7Fi32FWOOfhLdnUg"
youtube_channels[SEB]="https://www.youtube.com/channel/UCK3inMNRNAVUleEbpDU1k2g"
youtube_channels[SEB - Topic]="https://www.youtube.com/channel/UCy0G9iQtW-T7EyeJVZMaG6A"
youtube_channels[Sebastian Lague]="https://www.youtube.com/channel/UCmtyQOKKmrMVaKuRXz02jbQ"
youtube_channels[Seth Gueko]="https://www.youtube.com/channel/UCi8NwgKNP8qpp8n4DUTJvpg"
youtube_channels[SethBling]="https://www.youtube.com/channel/UC8aG3LDTDwNR1UQhSn9uVrw"
youtube_channels[Shayofficiel]="https://www.youtube.com/channel/UC_ckA7BVoVkUTty1LvJqVoQ"
youtube_channels[Simon Puech]="https://www.youtube.com/channel/UCMQSwUNSnMOP4IRysfeg8EA"
youtube_channels[SimonDev]="https://www.youtube.com/channel/UCEwhtpXrg5MmwlH04ANpL8A"
youtube_channels[SIMONY Musique]="https://www.youtube.com/channel/UCBC2uxcPkp-8iCL9pD2OsVw"
youtube_channels[Sixty Symbols]="https://www.youtube.com/channel/UCvBqzzvUBLCs8Y7Axb-jZew"
youtube_channels[SLIMKA]="https://www.youtube.com/channel/UC7GaaYKkVNyKHnHnkXalrlw"
youtube_channels[SmarterEveryDay]="https://www.youtube.com/channel/UC6107grRI4m0o2-emgoDnAA"
youtube_channels[Sneazzy]="https://www.youtube.com/channel/UC5f7mqpu4JipuK43PL9lnog"
youtube_channels[Sofyan]="https://www.youtube.com/channel/UCGWoTWsXJi1UtCjOiBHIsfw"
youtube_channels[SolangeTeParle]="https://www.youtube.com/channel/UCQfakletOMk9zXVRSHUdyDA"
youtube_channels[Son Lux]="https://www.youtube.com/channel/UCvaVEjRMc91tuAxO3b3JuQw"
youtube_channels[Soso Maness]="https://www.youtube.com/channel/UCNBsZQ6NvqRYpF5472QxlXA"
youtube_channels[Spider ZED]="https://www.youtube.com/channel/UCzJjSzJlY1V41u5lGVNwGtg"
youtube_channels[SpriNoirTv]="https://www.youtube.com/channel/UCKI8PEQkFi-aRktWXHK838w"
youtube_channels[SQUEEZIE]="https://www.youtube.com/channel/UCWeg2Pkate69NFdBeuRFTAw"
youtube_channels[SQUEEZIE GAMING]="https://www.youtube.com/channel/UCY-_QmcW09PHAImgVnKxU2g"
youtube_channels[Stand-up Maths]="https://www.youtube.com/channel/UCSju5G2aFaWMqn-_0YBtq5A"
youtube_channels[Steve Mould]="https://www.youtube.com/channel/UCEIwxahdLz7bap-VDs9h35A"
youtube_channels[String Theory FR]="https://www.youtube.com/channel/UCfxwT02Bu5R7l21uMAu8H1w"
youtube_channels[Studio Bagel]="https://www.youtube.com/channel/UCZ8kV8vuMdDLSerCIFfWnFQ"
youtube_channels[Stuff Made Here]="https://www.youtube.com/channel/UCj1VqrHhDte54oLgPG4xpuQ"
youtube_channels[Suzane]="https://www.youtube.com/channel/UCY0I0w7JbRyn-5p5Ni9Z9_A"
youtube_channels[Swing ODC]="https://www.youtube.com/channel/UC7Hb27QY77X11YZ-gxndpJg"
youtube_channels[Tech2Tech - Mikaël]="https://www.youtube.com/channel/UC4wj8LCLrOfgKrOVDLW4yOA"
youtube_channels[Techniques Spatiales]="https://www.youtube.com/channel/UCwf-gTeemly9VOVALdBXiTw"
youtube_channels[TEDx Talks]="https://www.youtube.com/channel/UCsT0YIqwnpJCM-mx7-gSA4Q"
youtube_channels[Tengo John]="https://www.youtube.com/channel/UC6NOeYQolq4rMPPkIisk9MQ"
youtube_channels[The 8-Bit Guy]="https://www.youtube.com/channel/UC8uT9cgJorJPWu7ITLGo9Ww"
youtube_channels[The Action Lab]="https://www.youtube.com/channel/UC1VLQPn9cYSqx8plbk9RxxQ"
youtube_channels[The Clash]="https://www.youtube.com/channel/UCWfAZudbGLAyrrEBaGuslNA"
youtube_channels[The Coding Train]="https://www.youtube.com/channel/UCvjgXvBlbQiydffZU7m1_aw"
youtube_channels[The Hop]="https://www.youtube.com/channel/UCrnYm9EWnNNS2x2lk92Js3A"
youtube_channels[The Marías]="https://www.youtube.com/channel/UChmZkdugBmAP_zpyzayv6VQ"
youtube_channels[The Pirouettes]="https://www.youtube.com/channel/UCc8u72IB8_MNi-lWGRw7xbw"
youtube_channels[thekooksofficial]="https://www.youtube.com/channel/UC3lSoOBQYPsZPYpgoC6_RVg"
youtube_channels[Thomas Gauthier]="https://www.youtube.com/channel/UCx0oS6YmHSbOMnN3vQvTR0Q"
youtube_channels[Tibees]="https://www.youtube.com/channel/UC52kszkc08-acFOuogFl5jw"
youtube_channels[Timmy Trumpet]="https://www.youtube.com/channel/UCd61k-5ykv_4RIbQg-Mpvrg"
youtube_channels[Todiefor]="https://www.youtube.com/channel/UCT2MY5cNK9ea8m86v-1MU7g"
youtube_channels[Tom Scott]="https://www.youtube.com/channel/UCBa659QWEk1AI4Tg--mrJ2A"
youtube_channels[Tones And I]="https://www.youtube.com/channel/UCQeiBlCcS4-XGwFjrvDn96w"
youtube_channels[Tove Lo]="https://www.youtube.com/channel/UCN7gplqpfnrT-mxjoTR4ENg"
youtube_channels[TrackZero]="https://www.youtube.com/channel/UC2nsQ2YLRqYNOzI3Rty58_Q"
youtube_channels[Trampsta]="https://www.youtube.com/channel/UCOlxGyNCuzG8xm5ogYM6OOQ"
youtube_channels[Trei Degete - Topic]="https://www.youtube.com/channel/UCeUqjjJlyNYIMGm-ieMgsHA"
youtube_channels[Trxns]="https://www.youtube.com/channel/UCnOuKKfBkvt2VsXcYSr8W2Q"
youtube_channels[Two Minute Papers]="https://www.youtube.com/channel/UCbfYPyITQ-7l4upoX8nvctg"
youtube_channels[Usagi Electric]="https://www.youtube.com/channel/UCE4xstUnu0YmkG-W9_PyYrQ"
youtube_channels[USKY]="https://www.youtube.com/channel/UCn3rDtMbhZGAb6L-avf_WvQ"
youtube_channels[Vald Sullyvan]="https://www.youtube.com/channel/UCUNv0EUZYhuelHXWoFLTqwg"
youtube_channels[vcubingx]="https://www.youtube.com/channel/UCv0nF8zWevEsSVcmz6mlw6A"
youtube_channels[VENLO]="https://www.youtube.com/channel/UCjTNeO1fF2dXsL3GyR6wqEg"
youtube_channels[Veritasium]="https://www.youtube.com/channel/UCHnyfMqiRRG1u-2MsSQLbXA"
youtube_channels[VIDEOCLUB]="https://www.youtube.com/channel/UC7fW7oNXyRDSxMOHVJE1jrA"
youtube_channels[Vihart]="https://www.youtube.com/channel/UCOGeU-1Fig3rrDjhm9Zs_wg"
youtube_channels[vins wazacrew]="https://www.youtube.com/channel/UC2GJz3_g-SBaVE8IzrYJgoQ"
youtube_channels[vladimir cauchemar]="https://www.youtube.com/channel/UC07udoHCKUb36kImuvm5zJw"
youtube_channels[Vlanx]="https://www.youtube.com/channel/UCZ3-PmXGBBFv-lZ6yYDlUbQ"
youtube_channels[Vons]="https://www.youtube.com/channel/UCXQyNNX6Q-2XtTPUhnTkrBw"
youtube_channels[Vsauce]="https://www.youtube.com/channel/UC6nSFpj9HTCZ5t-N3Rm3-HA"
youtube_channels[Vsauce2]="https://www.youtube.com/channel/UCqmugCqELzhIMNYnsjScXXw"
youtube_channels[VSOFFICIEL]="https://www.youtube.com/channel/UCgfBiRWckyGTT0m8D8omYPw"
youtube_channels[Wankil Studio - Laink et Terracid]="https://www.youtube.com/channel/UCYGjxo5ifuhnmvhPvCc3DJQ"
youtube_channels[Waxx]="https://www.youtube.com/channel/UCVBXlR7YhYUr-DfNG1XLrHA"
youtube_channels[Will Smith]="https://www.youtube.com/channel/UCKuHFYu3smtrl2AwwMOXOlg"
youtube_channels[Wintergatan]="https://www.youtube.com/channel/UCcXhhVwCT6_WqjkEniejRJQ"
youtube_channels[Y2K]="https://www.youtube.com/channel/UCjFSstOzzKPU8WjEySZpPvA"
youtube_channels[Yannic Kilcher]="https://www.youtube.com/channel/UCZHmQk67mSJgfCCTn7xBfew"
youtube_channels[Younès]="https://www.youtube.com/channel/UCQ5Te6_mT6DsW3wDPclnDRw"
youtube_channels[Youssoupha]="https://www.youtube.com/channel/UCcVrym0F4OFhLkrc-f4h2sg"
youtube_channels[Yung Gravy]="https://www.youtube.com/channel/UCLQPinZNWKlLBF7C_m2YP3g"
youtube_channels[YUNGBLUD]="https://www.youtube.com/channel/UCd3Llj2WWJh8ItfYl32eJ4Q"
youtube_channels[Yuzmv]="https://www.youtube.com/channel/UCLDJBuTfBXuaAMnlGYVr6mg"
youtube_channels[Zach Star]="https://www.youtube.com/channel/UCpCSAcbqs-sjEVfk_hMfY9w"
youtube_channels[Zapping Sauvage]="https://www.youtube.com/channel/UCAdyNOE80FsFPYlFliyXfwQ"
youtube_channels[Zed Yun Pavarotti]="https://www.youtube.com/channel/UC7yikfNqxwaU-XU5TRx8-pA"
youtube_channels[Zinée]="https://www.youtube.com/channel/UCYwe0x5pDu6AqBRDGqYYzqw"


# dm-bookman
bookman_show_source=1

# dm-sounds
sounds_dir="${HOME}/.config/dmscripts/dmsounds"

# dm-setbg
setbg_dir="${HOME}/Pictures/Wallpapers"
# Set this to 1 if you want to use imv and wayland, 0 if you want to use sxiv
# Note that sxiv is X11 only, you need to mark the image you want to use.
use_imv=1

# dm-maim
maim_dir="${HOME}/Screenshots"
maim_file_prefix="maim"

# dm-colpick config
declare -A colpick_list
colpick_list[black]="#282a36"
colpick_list[red]="#ff5555"
colpick_list[green]="#5af78e"
colpick_list[yellow]="#f1fa8c"
colpick_list[blue]="#57c7ff"
colpick_list[magenta]="#ff6ac1"
colpick_list[cyan]="#8be9fd"
colpick_list[white]="#f1f1f0"
colpick_list[orange]="#ffb86c"
colpick_list[purple]="#bd9cf9"

# dm-translate config

# dm-translate currently supports two translation services, LibreTranslate and Lingva Translate.
# LibreTranslate uses the free software (Expat/MIT licensed) Argos Translate library for translation.
# Lingva Translate uses the Google Translate (dis)service for translation, but this is fully server-side and Google will not see your IP.
# Both are free software services that can be self-hosted.
# If you want more languages (or need a specific language not in the Argos library) you should chose Lingva Translate.
# If you want to get away from Google and/or want a fully free software implementation you should use LibreTranslate.
# The choice is yours...
translate_service="libre"
# translate_service="lingva"
libretranslate_instance="https://libretranslate.de"
lingva_instance="https://lingva.ml"

# Uncomment to manually set the languages dm-translate will show
# LibreTranslate languages:
#   - `curl -Ss "https://libretranslate.de/languages" | jq`
# Lingva Translate languages:
#   - `curl -Ss "https://lingva.ml/api/v1/languages/source" | jq`
# translate_list="manual"
# declare -A lang_map
# lang_map[Spanish]=es
# lang_map[English]=en
# lang_map[Automatic]=auto

# dm-weather config
declare -A weather_location
# weather_location[New York]="New+York"
# weather_opts="m" # Always use metric units (celsius)
# weather_opts="u" # Always use US units (fahrenheit)
# see: https://github.com/chubin/wttr.in

# dm-currencies config

# Chose how you want to display the currencies (default: "names")
# currency_names="codes"

# "auto" will get currencies dynamically, "manual" will only use the currencies you define (default: "auto")
# defined currencies will still be included when set to auto
# currency_method="manual"

declare -A currencies
# currencies[Dollar]="USD"
# currencies[Pound]="GBP"
# currencies[Monero]="XMR"
# see: https://rate.sx/:currencies and https://rate.sx/:coins

_revision=22

