#! /usr/bin/fish
#             ___
#       ____ |__ \ ____              _____      personal page: https://a2n-s.github.io/ 
#      / __ `/_/ // __ \   ______   / ___/      github   page: https://github.com/a2n-s 
#     / /_/ / __// / / /  /_____/  (__  )       my   dotfiles: https://github.com/a2n-s/dotfiles 
#     \__,_/____/_/ /_/           /____/
#                               _____             __   __                                       __   __
#             _________  ____  / __(_)___ _     _/_/  / /_  _________ _      ______ ___       _/_/  / /_  _________ _      ______ ___  __________
#            / ___/ __ \/ __ \/ /_/ / __ `/   _/_/   / __ \/ ___/ __ \ | /| / / __ `__ \    _/_/   / __ \/ ___/ __ \ | /| / / __ `__ \/ ___/ ___/
#      _    / /__/ /_/ / / / / __/ / /_/ /  _/_/    / /_/ (__  ) /_/ / |/ |/ / / / / / /  _/_/    / /_/ (__  ) /_/ / |/ |/ / / / / / / /  / /__
#     (_)   \___/\____/_/ /_/_/ /_/\__, /  /_/     /_.___/____/ .___/|__/|__/_/ /_/ /_/  /_/     /_.___/____/ .___/|__/|__/_/ /_/ /_/_/   \___/
#                                 /____/                     /_/                                           /_/
#
# Description:  my config of bspwm.
# Dependencies: sxhkd
# License:      https://github.com/a2n-s/dotfiles/blob/main/LICENSE 
# Contributors: Stevan Antoine
#
#               Table of Content:
#                 BSPWM initialization.
#                 BSPWM monitor connection.
#                 BSPWM configuration.
#                 BSPWM coloring.
#                 BSPWM rules.
#                 BSPWM autostart.
#

# >>> BSPWM initialization.
feh --bg-fill --randomize ~/repos/wallpapers/wallpapers/
# set -U SHELL /bin/sh
# set -U SXHKD_SHELL sh
# set -U SHELL /bin/bash
# set -U SXHKD_SHELL /bin/bash
pgrep -x sxhkd > /dev/null || sxhkd &
bash $HOME/.config/polybar/launch.sh --forest &
killall -q xautolock
xautolock -time 10 -locker ~/scripts/slock-cst.sh &
xset s 0
xset -dpms

# >>> BSPWM monitor connection.
bspc monitor eDP-1  -n 1 -d I II III IV V
bspc monitor HDMI-2 -n 2 -d VI VII VIII IX X

# >>> BSPWM configuration.
#bspc config border_radius                8
bspc config border_width                  4
bspc config window_gap                    4
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.618
bspc config borderless_monocle            false
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# >>> BSPWM coloring.
bspc config normal_border_color   "#4c566a"
bspc config active_border_color   "#1e1e1e"
bspc config focused_border_color  "#ee81ac"
bspc config presel_feedback_color "#272156"
bspc config urgent_border_color   "#dd2727"

# >>> BSPWM rules.
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# >>> BSPWM autostart.
# alacritty
